#pragma once
#include <Arduino.h>

static const char kWebPage[] PROGMEM = R"HTML(<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KNX Analyzer</title><style>
:root{font-family:system-ui,sans-serif;color:#e8f2f5;background:#0b1720}*{box-sizing:border-box}body{margin:0}header{padding:18px 22px;background:#122632;border-bottom:1px solid #29505d}h1{font-size:1.3rem;margin:0;color:#68d9e7}small,.muted{color:#9db6bd}nav{display:flex;gap:4px;overflow:auto;padding:9px 12px;background:#10232f}nav button{white-space:nowrap;background:transparent;border:0;color:#b9cdd1;padding:9px 12px;border-radius:7px}nav button.active{background:#1d4351;color:white}main{max-width:1000px;margin:auto;padding:18px}h2{font-size:1.2rem}section{display:none}section.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{background:#142b37;border:1px solid #2d4b55;border-radius:10px;padding:16px;min-height:95px}.label{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;color:#9bb8be}.value{font-size:1.35rem;margin-top:8px;word-break:break-word}.actions{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}button.action{background:#1b7284;color:white;border:0;border-radius:8px;padding:12px 16px;font-weight:700;cursor:pointer}button.action.alt{background:#344a54}button.action.warn{background:#9d494b}button:disabled{opacity:.45}canvas{width:100%;height:330px;background:#07141b;border:1px solid #34515b;border-radius:8px}input,select{display:block;width:100%;padding:11px;background:#09202a;color:white;border:1px solid #41616a;border-radius:7px;margin:6px 0 12px}form{max-width:550px}.notice{padding:10px;background:#1a3944;border-radius:7px;margin:12px 0}.mono{font-family:ui-monospace,monospace}footer{padding:20px;color:#78989f;text-align:center}
</style></head><body><header><h1>KNX ANALYZER</h1><small id="connection">Connecting…</small></header><nav id="nav"></nav><main>
<section id="dashboard" class="active"><h2>Dashboard</h2><div class="grid" id="cards"></div><div class="actions"><button class="action" onclick="command('/api/analysis/start')">START ANALYSIS</button><button class="action warn" onclick="command('/api/analysis/stop')">STOP ANALYSIS</button></div></section>
<section id="scope"><h2>GPIO5 Scope</h2><p id="scopeMeta" class="mono">Waiting for data…</p><canvas id="plot" width="800" height="330"></canvas><div class="actions"><button class="action" onclick="arm('rising')">ARM RISING</button><button class="action" onclick="arm('falling')">ARM FALLING</button><button class="action alt" onclick="arm('manual')">ARM MANUAL</button><button class="action alt" onclick="command('/api/scope/trigger')">MANUAL TRIGGER</button><button class="action alt" onclick="command('/api/scope/clear')">CLEAR</button></div></section>
<section id="events"><h2>Events</h2><p class="notice">Not implemented yet</p></section><section id="sessions"><h2>Sessions</h2><p class="notice">Not implemented yet</p></section>
<section id="configuration"><h2>Wi-Fi configuration</h2><p class="notice">Primary and backup profiles are stored on this device. Passwords are never shown here.</p><button class="action alt" onclick="scan()">SCAN NETWORKS</button><div id="networks" class="muted"></div><form onsubmit="saveWifi(event)"><label>Profile<select id="slot"><option value="1">Primary</option><option value="2">Backup</option></select></label><label>SSID<input id="ssid" maxlength="32" required></label><label>Password<input id="password" type="password" maxlength="63" autocomplete="new-password"></label><button class="action" type="submit">SAVE & CONNECT</button></form><p id="wifiMessage"></p></section>
<section id="system"><h2>System</h2><div class="grid" id="systemCards"></div></section>
</main><footer>LAN only · GPIO5 scope · no SD writes</footer><script>
const names=['dashboard','scope','events','sessions','configuration','system'];let page='dashboard',latest=null,ws=null;const $=x=>document.getElementById(x);
function show(n){page=n;for(const id of names)$(id).classList.toggle('active',id===n);for(const b of $('nav').children)b.classList.toggle('active',b.dataset.page===n);if(n==='scope')loadWave()}
for(const n of names){const b=document.createElement('button');b.textContent=n[0].toUpperCase()+n.slice(1);b.dataset.page=n;b.onclick=()=>show(n);$('nav').appendChild(b)}show('dashboard');
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(k,v){return '<div class="card"><div class="label">'+esc(k)+'</div><div class="value">'+esc(v)+'</div></div>'}
function render(s){latest=s;$('connection').textContent=s.wifi.mode+' · '+(s.wifi.ip||'no IP')+' · '+(ws&&ws.readyState===1?'live':'polling');$('cards').innerHTML=card('Analysis',s.analysis.state)+card('ADC',s.adc.ready?'READY':'ERROR')+card('Sample rate',((s.adc.measured_hz||0)/1000).toFixed(1)+' kS/s')+card('Overruns',s.adc.overruns)+card('Heap free',s.heap.free+' B')+card('Wi-Fi',s.wifi.ssid||s.wifi.mode)+card('IP / RSSI',(s.wifi.ip||'—')+' / '+(s.wifi.rssi||'—')+' dBm')+card('SD',s.sd.ready?'READY':'UNAVAILABLE')+card('KNX','NOT CONNECTED')+card('VBUS','NOT CONNECTED')+card('Events',0);$('systemCards').innerHTML=card('Firmware',s.firmware)+card('Uptime',Math.floor(s.uptime_ms/1000)+' s')+card('Heap minimum',s.heap.minimum+' B')+card('Largest block',s.heap.largest+' B')+card('Flash',s.flash_bytes+' B')+card('Wi-Fi',s.wifi.mode)}
async function get(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(await r.text());return r.json()}
async function command(path,body={}){try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());await refresh();if(page==='scope')loadWave()}catch(e){alert(e.message)}}
const arm=mode=>command('/api/scope/arm',{mode});
async function refresh(){try{render(await get('/api/status'))}catch(e){$('connection').textContent='Disconnected'}}
async function loadWave(){if(page!=='scope')return;try{const d=await get('/api/scope/capture');drawWave(d);$('scopeMeta').textContent=(d.state||'EMPTY')+' · '+d.samples+' samples · min/max '+d.min_raw+'/'+d.max_raw+' · '+((d.sample_rate_hz||0)/1000).toFixed(1)+' kS/s · pre/post '+d.pre_samples+'/'+d.post_samples}catch(e){$('scopeMeta').textContent='Scope unavailable'}}
function drawWave(d){const c=$('plot'),g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#07141b';g.fillRect(0,0,w,h);g.strokeStyle='#25434d';for(let i=1;i<4;i++){g.beginPath();g.moveTo(0,i*h/4);g.lineTo(w,i*h/4);g.stroke()}if(!d.low||!d.low.length)return;const y=v=>h-1-v*(h-1)/4095;g.strokeStyle='#55dfec';g.beginPath();for(let i=0;i<d.low.length;i++){const x=i*w/d.low.length;g.moveTo(x,y(d.low[i]));g.lineTo(x,y(d.high[i]))}g.stroke();if(d.state==='CAPTURED'){g.strokeStyle='#ff6770';g.beginPath();const x=w*d.pre_samples/d.samples;g.moveTo(x,0);g.lineTo(x,h);g.stroke()}}
async function scan(){await get('/api/wifi/networks?refresh=1');for(let i=0;i<12;i++){const d=await get('/api/wifi/networks');if(!d.scanning){$('networks').replaceChildren();for(const n of d.networks){const b=document.createElement('button');b.className='action alt';b.textContent=n.ssid+' ('+n.rssi+' dBm)';b.onclick=()=>{$('ssid').value=n.ssid};$('networks').appendChild(b)}if(!d.networks.length)$('networks').textContent='No networks found';return}$('networks').textContent='Scanning...';await new Promise(resolve=>setTimeout(resolve,1000))}}
async function saveWifi(e){e.preventDefault();const body={slot:Number($('slot').value),ssid:$('ssid').value,password:$('password').value};try{const r=await fetch('/api/wifi/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());$('wifiMessage').textContent='Saved. Connecting; this page may disconnect while the ESP joins your LAN.';$('password').value=''}catch(err){$('wifiMessage').textContent=err.message}}
function connect(){try{ws=new WebSocket('ws://'+location.hostname+':81/');ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='status')render(d.data)}catch(_){}};ws.onclose=()=>setTimeout(connect,2000)}catch(_){setTimeout(connect,2000)}}connect();refresh();setInterval(()=>{if(!ws||ws.readyState!==1)refresh();if(page==='scope')loadWave()},1500);
</script></body></html>)HTML";
