#include <Arduino.h>
#include <esp_adc/adc_continuous.h>

constexpr uint32_t SAMPLE_RATE=83333, FRAME_BYTES=1024, POOL_BYTES=49152;
constexpr uint64_t PHASE_US=10000000ULL;
constexpr uint32_t HIST_BINS=98, TOP_N=12, THRESH_N=9;
const uint32_t thresholds[THRESH_N]={50,75,100,150,200,300,500,750,1000};
adc_continuous_handle_t adc=nullptr;
alignas(4) uint8_t frame[FRAME_BYTES];
volatile uint32_t dmaOverflowIsr=0;
enum class State{BACKGROUND,WAIT_TRAFFIC,TRAFFIC,DONE}; State state=State::BACKGROUND;
struct Stats{uint64_t count=0,sum=0,hist[HIST_BINS]{},above[THRESH_N]{};uint32_t min=UINT32_MAX,max=0;};
struct Peak{uint64_t sample=0;uint32_t d[4]{};};
Stats ds[4];Peak tops[4][TOP_N]{};uint16_t history[8]{};uint8_t histPos=0,histCount=0;
uint64_t phaseStartUs=0,sampleIndex=0,adcCount=0,adcSum=0;uint16_t adcMin=UINT16_MAX,adcMax=0;uint32_t phaseOverflowStart=0;

bool IRAM_ATTR onOverflow(adc_continuous_handle_t,const adc_continuous_evt_data_t*,void*){++dmaOverflowIsr;return false;}
uint32_t hbin(uint32_t v){if(v<64)return v;if(v<128)return 64+(v-64)/4;if(v<256)return 80+(v-128)/16;if(v<512)return 88+(v-256)/64;if(v<1024)return 92+(v-512)/256;if(v<2048)return 94;if(v<4096)return 95;if(v<8192)return 96;return 97;}
void resetPhase(){memset(ds,0,sizeof(ds));for(auto&x:ds)x.min=UINT32_MAX;memset(tops,0,sizeof(tops));memset(history,0,sizeof(history));histPos=histCount=0;adcCount=adcSum=0;adcMin=UINT16_MAX;adcMax=0;phaseOverflowStart=dmaOverflowIsr;phaseStartUs=esp_timer_get_time();}
uint32_t peakValue(uint8_t detector,uint8_t slot){return tops[detector][slot].d[detector];}
void updateTop(uint8_t detector,const Peak&p){uint8_t slot=0;for(uint8_t i=1;i<TOP_N;i++)if(peakValue(detector,i)<peakValue(detector,slot))slot=i;if(p.d[detector]>peakValue(detector,slot))tops[detector][slot]=p;}
void processSample(uint16_t v){uint64_t idx=sampleIndex++;++adcCount;adcSum+=v;if(v<adcMin)adcMin=v;if(v>adcMax)adcMax=v;if(histCount<8){history[histPos]=v;histPos=(histPos+1)&7;++histCount;return;}uint16_t x1=history[(histPos+7)&7],x2=history[(histPos+6)&7],x3=history[(histPos+5)&7],x4=history[(histPos+4)&7],x5=history[(histPos+3)&7],x6=history[(histPos+2)&7],x7=history[(histPos+1)&7];Peak p{};p.sample=idx;p.d[0]=abs(int32_t(v)-int32_t(x2));p.d[1]=abs(int32_t(v)-int32_t(x4));p.d[2]=abs(int32_t(v)-int32_t(history[histPos]));p.d[3]=abs(int32_t(uint32_t(v)+x1+x2+x3)-int32_t(uint32_t(x4)+x5+x6+x7));for(uint8_t k=0;k<4;k++){Stats&s=ds[k];uint32_t z=p.d[k];++s.count;s.sum+=z;if(z<s.min)s.min=z;if(z>s.max)s.max=z;++s.hist[hbin(z)];for(uint8_t t=0;t<THRESH_N;t++)if(z>thresholds[t])++s.above[t];updateTop(k,p);}history[histPos]=v;histPos=(histPos+1)&7;}
void printPhase(const char*name){const char*dn[4]={"D2","D4","D8","D44"};uint64_t dur=esp_timer_get_time()-phaseStartUs;Serial.printf("{\"type\":\"ADC\",\"population\":\"%s\",\"duration_us\":%llu,\"count\":%llu,\"mean\":%.6f,\"min\":%u,\"max\":%u,\"amplitude\":%u,\"dma_overflow\":%u}\n",name,dur,adcCount,double(adcSum)/adcCount,adcMin,adcMax,adcMax-adcMin,dmaOverflowIsr-phaseOverflowStart);for(uint8_t k=0;k<4;k++){Stats&s=ds[k];Serial.printf("{\"type\":\"DETECTOR\",\"population\":\"%s\",\"name\":\"%s\",\"count\":%llu,\"mean\":%.6f,\"max\":%u,\"hist\":[",name,dn[k],s.count,double(s.sum)/s.count,s.max);for(uint8_t i=0;i<HIST_BINS;i++){if(i)Serial.print(',');Serial.print(s.hist[i]);}Serial.print("],\"above\":[");for(uint8_t i=0;i<THRESH_N;i++){if(i)Serial.print(',');Serial.print(s.above[i]);}Serial.println("]}");}for(uint8_t k=0;k<4;k++)for(uint8_t i=0;i<TOP_N;i++){Peak&p=tops[k][i];if(p.d[k])Serial.printf("{\"type\":\"PEAK\",\"population\":\"%s\",\"rank_detector\":\"%s\",\"sample_index\":%llu,\"D2\":%u,\"D4\":%u,\"D8\":%u,\"D44\":%u}\n",name,dn[k],p.sample,p.d[0],p.d[1],p.d[2],p.d[3]);}}
bool initAdc(){adc_continuous_handle_cfg_t h{};h.max_store_buf_size=POOL_BYTES;h.conv_frame_size=FRAME_BYTES;if(adc_continuous_new_handle(&h,&adc)!=ESP_OK)return false;adc_digi_pattern_config_t p{};p.atten=ADC_ATTEN_DB_12;p.channel=ADC_CHANNEL_5;p.unit=ADC_UNIT_1;p.bit_width=SOC_ADC_DIGI_MAX_BITWIDTH;adc_continuous_config_t c{};c.pattern_num=1;c.adc_pattern=&p;c.sample_freq_hz=SAMPLE_RATE;c.conv_mode=ADC_CONV_SINGLE_UNIT_1;c.format=ADC_DIGI_OUTPUT_FORMAT_TYPE2;if(adc_continuous_config(adc,&c)!=ESP_OK)return false;adc_continuous_evt_cbs_t cb{};cb.on_pool_ovf=onOverflow;return adc_continuous_register_event_callbacks(adc,&cb,nullptr)==ESP_OK;}
void setup(){Serial.begin(115200);delay(1200);if(!initAdc()||adc_continuous_start(adc)!=ESP_OK){Serial.println("ADC_INIT_ERROR");return;}resetPhase();Serial.println("BACKGROUND 10 seconds - no intentional traffic");}
void loop(){uint32_t bytes=0;esp_err_t er=adc_continuous_read(adc,frame,sizeof(frame),&bytes,50);bool measuring=state==State::BACKGROUND||state==State::TRAFFIC;if(er==ESP_OK&&measuring)for(uint32_t off=0;off+SOC_ADC_DIGI_RESULT_BYTES<=bytes;off+=SOC_ADC_DIGI_RESULT_BYTES){auto*r=(adc_digi_output_data_t*)(frame+off);if(r->type2.channel==ADC_CHANNEL_5)processSample(r->type2.data);}if(state==State::WAIT_TRAFFIC&&Serial.available()){String c=Serial.readStringUntil('\n');c.trim();c.toUpperCase();if(c=="GO"||c=="TRAFFIC"){resetPhase();state=State::TRAFFIC;Serial.println("FORCED_TRAFFIC 10 seconds");}}if(measuring&&esp_timer_get_time()-phaseStartUs>=PHASE_US){if(state==State::BACKGROUND){printPhase("BACKGROUND");state=State::WAIT_TRAFFIC;Serial.println(">>> PROVOQUE MAINTENANT DU TRAFIC KNX AVEC ETS <<<");Serial.println("En attente de GO; ADC draine en continu.");}else{printPhase("FORCED_TRAFFIC");state=State::DONE;adc_continuous_stop(adc);Serial.println("TEST_TERMINE");}}}