#include <Arduino.h>
#include <SPI.h>
#include <SD.h>
#include <esp_adc/adc_continuous.h>
#include <esp_heap_caps.h>
#include <esp_memory_utils.h>
#include <atomic>

constexpr uint32_t SAMPLE_RATE=83333,SD_HZ=4000000;
constexpr size_t BUFFER_BYTES=16*1024,SAMPLES_PER_BUFFER=BUFFER_BYTES/2,BUFFER_COUNT=2;
constexpr size_t DMA_BYTES=1024,DMA_POOL_BYTES=49152;
constexpr uint64_t TEST_US=600ULL*1000000ULL;
struct Buffer{uint32_t count;uint16_t samples[SAMPLES_PER_BUFFER];};
Buffer*buffers[BUFFER_COUNT]{};QueueHandle_t freeQ=nullptr,readyQ=nullptr;adc_continuous_handle_t adc=nullptr;File raw;
std::atomic<bool> active{false},stopping{false};
std::atomic<uint64_t> acquired{0},written{0},lost{0},sdBytes{0},writeCalls{0},writeTimeUs{0};
std::atomic<uint32_t> dmaOverflow{0},bufferOverflow{0},sdErrors{0},shortWrites{0},zeroWrites{0},writeMaxUs{0},queueMax{0};
volatile uint32_t dmaOverflowIsr=0;uint64_t startUs=0;String path;
void max32(std::atomic<uint32_t>&v,uint32_t n){uint32_t o=v.load();while(n>o&&!v.compare_exchange_weak(o,n)){} }
bool IRAM_ATTR onOverflow(adc_continuous_handle_t,const adc_continuous_evt_data_t*,void*){++dmaOverflowIsr;return false;}
bool initAdc(){adc_continuous_handle_cfg_t h{};h.max_store_buf_size=DMA_POOL_BYTES;h.conv_frame_size=DMA_BYTES;if(adc_continuous_new_handle(&h,&adc)!=ESP_OK)return false;adc_digi_pattern_config_t p{};p.atten=ADC_ATTEN_DB_12;p.channel=ADC_CHANNEL_5;p.unit=ADC_UNIT_1;p.bit_width=SOC_ADC_DIGI_MAX_BITWIDTH;adc_continuous_config_t c{};c.pattern_num=1;c.adc_pattern=&p;c.sample_freq_hz=SAMPLE_RATE;c.conv_mode=ADC_CONV_SINGLE_UNIT_1;c.format=ADC_DIGI_OUTPUT_FORMAT_TYPE2;if(adc_continuous_config(adc,&c)!=ESP_OK)return false;adc_continuous_evt_cbs_t cb{};cb.on_pool_ovf=onOverflow;return adc_continuous_register_event_callbacks(adc,&cb,nullptr)==ESP_OK;}
void adcTask(void*){alignas(4)uint8_t dma[DMA_BYTES];Buffer*cur=nullptr;while(true){if(!active){if(cur&&cur->count){xQueueSend(readyQ,&cur,portMAX_DELAY);cur=nullptr;}vTaskDelay(pdMS_TO_TICKS(2));continue;}uint32_t bytes=0;esp_err_t e=adc_continuous_read(adc,dma,sizeof(dma),&bytes,50);dmaOverflow=dmaOverflowIsr;if(e==ESP_ERR_TIMEOUT)continue;if(e!=ESP_OK)continue;for(uint32_t off=0;off+SOC_ADC_DIGI_RESULT_BYTES<=bytes;off+=SOC_ADC_DIGI_RESULT_BYTES){const auto*r=reinterpret_cast<const adc_digi_output_data_t*>(dma+off);if(r->type2.channel!=ADC_CHANNEL_5)continue;++acquired;if(!cur&&xQueueReceive(freeQ,&cur,0)!=pdTRUE){++lost;++bufferOverflow;continue;}cur->samples[cur->count++]=r->type2.data;if(cur->count==SAMPLES_PER_BUFFER){xQueueSend(readyQ,&cur,portMAX_DELAY);cur=nullptr;max32(queueMax,uxQueueMessagesWaiting(readyQ));}}}}
void writerTask(void*){uint64_t sinceFlush=0;while(true){Buffer*b=nullptr;if(xQueueReceive(readyQ,&b,pdMS_TO_TICKS(20))==pdTRUE){size_t req=b->count*2;uint64_t began=esp_timer_get_time();size_t n=raw?raw.write(reinterpret_cast<uint8_t*>(b->samples),req):0;uint32_t dt=uint32_t(esp_timer_get_time()-began);++writeCalls;writeTimeUs+=dt;max32(writeMaxUs,dt);if(n==req){written+=b->count;sdBytes+=n;sinceFlush+=n;}else{++shortWrites;if(n==0)++zeroWrites;++sdErrors;lost+=b->count;active=false;Serial.printf("{\"type\":\"SD_ERROR\",\"requested\":%u,\"actual\":%u}\n",unsigned(req),unsigned(n));}b->count=0;xQueueSend(freeQ,&b,portMAX_DELAY);if(sinceFlush>=170000&&raw){raw.flush();sinceFlush=0;}}if(stopping&&uxQueueMessagesWaiting(readyQ)==0){if(raw)raw.flush();stopping=false;}}}
void finish(){if(!active&&!stopping)return;active=false;adc_continuous_stop(adc);delay(20);stopping=true;uint32_t deadline=millis()+5000;while(stopping&&int32_t(deadline-millis())>0)delay(2);if(raw){raw.flush();raw.close();}uint64_t duration=esp_timer_get_time()-startUs;bool pass=duration>=TEST_US&&lost==0&&dmaOverflow==0&&bufferOverflow==0&&sdErrors==0&&sdBytes==written*2;Serial.printf("{\"type\":\"RESULT\",\"duration_us\":%llu,\"requested_hz\":%u,\"adc_hz\":%.1f,\"acquired\":%llu,\"written\":%llu,\"lost\":%llu,\"dma_overflow\":%u,\"buffer_overflow\":%u,\"sd_bytes\":%llu,\"sd_Bps\":%.1f,\"write_calls\":%llu,\"short_writes\":%u,\"zero_writes\":%u,\"sd_errors\":%u,\"write_avg_us\":%llu,\"write_max_us\":%u,\"bytes_match\":%s,\"pass\":%s,\"file\":\"%s\"}\n",duration,SAMPLE_RATE,double(acquired.load())*1000000.0/duration,acquired.load(),written.load(),lost.load(),dmaOverflow.load(),bufferOverflow.load(),sdBytes.load(),double(sdBytes.load())*1000000.0/duration,writeCalls.load(),shortWrites.load(),zeroWrites.load(),sdErrors.load(),writeCalls?writeTimeUs/writeCalls:0,writeMaxUs.load(),sdBytes==written*2?"true":"false",pass?"true":"false",path.c_str());}
void start(){char name[48];snprintf(name,sizeof(name),"/adc-raw-%08lX.bin",(unsigned long)esp_random());path=name;raw=SD.open(path,FILE_WRITE);if(!raw){Serial.println("{\"type\":\"OPEN_ERROR\"}");return;}acquired=written=lost=sdBytes=writeCalls=writeTimeUs=0;dmaOverflow=bufferOverflow=sdErrors=shortWrites=zeroWrites=writeMaxUs=queueMax=0;dmaOverflowIsr=0;startUs=esp_timer_get_time();active=true;if(adc_continuous_start(adc)!=ESP_OK){active=false;raw.close();Serial.println("{\"type\":\"ADC_START_ERROR\"}");return;}Serial.printf("{\"type\":\"START\",\"file\":\"%s\"}\n",path.c_str());}
void setup(){Serial.begin(115200);delay(1200);pinMode(14,OUTPUT);digitalWrite(14,HIGH);SPI.begin(1,3,2,14);bool sd=SD.begin(4,SPI,SD_HZ);freeQ=xQueueCreate(BUFFER_COUNT,sizeof(Buffer*));readyQ=xQueueCreate(BUFFER_COUNT,sizeof(Buffer*));for(size_t i=0;i<BUFFER_COUNT;i++){buffers[i]=static_cast<Buffer*>(heap_caps_calloc(1,sizeof(Buffer),MALLOC_CAP_INTERNAL|MALLOC_CAP_DMA|MALLOC_CAP_8BIT));if(!buffers[i]){Serial.println("BUFFER_ALLOC_ERROR");while(true)delay(1000);}xQueueSend(freeQ,&buffers[i],portMAX_DELAY);}bool a=initAdc();xTaskCreate(adcTask,"adc",4096,nullptr,4,nullptr);xTaskCreate(writerTask,"writer",4096,nullptr,2,nullptr);Serial.printf("{\"type\":\"BOOT\",\"sd\":%s,\"sd_hz\":%u,\"adc\":%s,\"buffers\":%u,\"buffer_bytes\":%u,\"buffer0\":\"%p\",\"internal\":%s,\"dma_capable\":%s,\"heap\":%u}\n",sd?"true":"false",SD_HZ,a?"true":"false",unsigned(BUFFER_COUNT),unsigned(BUFFER_BYTES),buffers[0],esp_ptr_internal(buffers[0])?"true":"false",esp_ptr_dma_capable(buffers[0])?"true":"false",ESP.getFreeHeap());}
void loop(){if(active&&esp_timer_get_time()-startUs>=TEST_US)finish();if(sdErrors&&active)finish();if(Serial.available()){String c=Serial.readStringUntil('\n');c.trim();c.toUpperCase();if(c=="RUN")start();else if(c=="STOP")finish();}delay(2);}