param([string]$WorkRoot=(Join-Path $env:TEMP 'knx-ls5-recovery'))
$ErrorActionPreference='Stop';if(Test-Path $WorkRoot){Remove-Item -LiteralPath $WorkRoot -Recurse -Force};New-Item -ItemType Directory -Path $WorkRoot|Out-Null
Add-Type -TypeDefinition @'
using System;public static class HarnessCrc{static readonly uint[]T=B();static uint[]B(){var t=new uint[256];for(uint i=0;i<256;i++){uint c=i;for(int k=0;k<8;k++)c=(c&1)!=0?0xEDB88320U^(c>>1):c>>1;t[i]=c;}return t;}public static uint U(uint s,byte[]b){uint c=~s;foreach(byte x in b)c=T[(c^x)&255]^(c>>8);return ~c;}public static uint Txt(string s){return U(0,System.Text.Encoding.UTF8.GetBytes(s));}}
'@
$utf8=New-Object Text.UTF8Encoding($false);function W($p,$s){[IO.File]::WriteAllText($p,$s,$utf8)}
function Hex([uint32]$v){'{0:X8}'-f$v}
function Start($d){W (Join-Path $d 'session-start.json') '{"record_type":"SESSION_START","schema_version":"knx-long-session-1.0","session_id":"00000000-0000-4000-8000-000000000001"}';W (Join-Path $d 'chunk-index.jsonl') '';W (Join-Path $d 'events.jsonl') ''}
function ChunkLine($seq,$start,$segment,$offset,[byte[]]$bytes){$crc=Hex([HarnessCrc]::U(0,$bytes));return '{"record_type":"CHUNK","seq":"'+$seq+'","sample_start":"'+$start+'","sample_end":"'+($start+($bytes.Length/2))+'","sample_count":'+($bytes.Length/2)+',"segment_index":'+$segment+',"segment_offset":"'+$offset+'","raw_bytes":'+$bytes.Length+',"crc32":"'+$crc+'"}'}
function Checkpoint($id,$ordinal,$seq,$end,$seg,$segBytes,$sessionBytes,$segCrc,$sessionCrc){$p='{"record_type":"CHECKPOINT","checkpoint_id":"'+$id+'","session_id":"00000000-0000-4000-8000-000000000001","segment_index":'+$seg+',"last_chunk_ordinal":"'+$ordinal+'","last_chunk_seq":"'+$seq+'","sample_end":"'+$end+'","segment_raw_bytes":"'+$segBytes+'","session_raw_bytes":"'+$sessionBytes+'","segment_crc32":"'+(Hex $segCrc)+'","session_crc32":"'+(Hex $sessionCrc)+'","completed_events_observed":0,"timestamp_sample":"'+$end+'"';return $p+',"record_crc32":"'+(Hex([HarnessCrc]::Txt($p)))+'"}'}
$a=[byte[]](0..15);$b=[byte[]](16..31);$crcA=[HarnessCrc]::U(0,$a);$crcAB=[HarnessCrc]::U($crcA,$b);$cases=@()
foreach($name in 'A_SILENCE','B_RAW_WRITE','C_EVENT_ACTIVE','D_METADATA_WRITE','E_CHECKPOINT_WRITE','F_BEFORE_ROTATION'){$d=Join-Path $WorkRoot $name;New-Item -ItemType Directory $d|Out-Null;Start $d;[IO.File]::WriteAllBytes((Join-Path $d 'raw-0000.bin'),$a+$b);W (Join-Path $d 'segments.jsonl') "{`"record_type`":`"SEGMENT_OPEN`",`"segment_index`":0,`"filename`":`"raw-0000.bin`",`"sample_start`":`"0`",`"state`":`"OPEN`"}`n";W (Join-Path $d 'chunks.jsonl') ((ChunkLine 1 0 0 0 $a)+"`n"+(ChunkLine 2 8 0 16 $b)+"`n");W (Join-Path $d 'checkpoints.jsonl') ((Checkpoint 1 1 1 8 0 16 16 $crcA $crcA)+"`n");$cases+=,$d}
Add-Content -LiteralPath (Join-Path $WorkRoot 'C_EVENT_ACTIVE\events.jsonl') -Value '{"record_type":"EVENT","event_id":"1","sample_start":"0","sample_end":"8"}'
[IO.File]::AppendAllText((Join-Path $WorkRoot 'C_EVENT_ACTIVE\events.jsonl'),'{"record_type":"EVENT"',$utf8)
[IO.File]::AppendAllText((Join-Path $WorkRoot 'D_METADATA_WRITE\chunks.jsonl'),'{"record_type":"CHUNK"',$utf8)
[IO.File]::AppendAllText((Join-Path $WorkRoot 'E_CHECKPOINT_WRITE\checkpoints.jsonl'),'{"record_type":"CHECKPOINT"',$utf8)
$g=Join-Path $WorkRoot 'G_AFTER_SEGMENT_OPEN';New-Item -ItemType Directory $g|Out-Null;Start $g;[IO.File]::WriteAllBytes((Join-Path $g 'raw-0000.bin'),$a);[IO.File]::WriteAllBytes((Join-Path $g 'raw-0001.bin'),[byte[]]@());W (Join-Path $g 'chunks.jsonl') ((ChunkLine 1 0 0 0 $a)+"`n");W (Join-Path $g 'checkpoints.jsonl') '';W (Join-Path $g 'segments.jsonl') ('{"record_type":"SEGMENT_OPEN","segment_index":0,"filename":"raw-0000.bin","sample_start":"0","state":"OPEN"}' +"`n"+'{"record_type":"SEGMENT_COMPLETE","segment_index":0,"filename":"raw-0000.bin","sample_start":"0","sample_end":"8","raw_bytes":"16","chunk_count":1,"crc32":"'+(Hex $crcA)+'","state":"COMPLETE"}' +"`n"+'{"record_type":"SEGMENT_OPEN","segment_index":1,"filename":"raw-0001.bin","sample_start":"8","state":"OPEN"}' +"`n");$cases+=,$g
$h=Join-Path $WorkRoot 'H_MULTIPLE_COMPLETE';New-Item -ItemType Directory $h|Out-Null;Start $h;[IO.File]::WriteAllBytes((Join-Path $h 'raw-0000.bin'),$a);[IO.File]::WriteAllBytes((Join-Path $h 'raw-0001.bin'),$b);[IO.File]::WriteAllBytes((Join-Path $h 'raw-0002.bin'),[byte[]]@());W (Join-Path $h 'chunks.jsonl') ((ChunkLine 1 0 0 0 $a)+"`n"+(ChunkLine 2 8 1 0 $b)+"`n");W (Join-Path $h 'checkpoints.jsonl') '';W (Join-Path $h 'segments.jsonl') ('{"record_type":"SEGMENT_OPEN","segment_index":0,"filename":"raw-0000.bin","sample_start":"0","state":"OPEN"}' +"`n"+'{"record_type":"SEGMENT_COMPLETE","segment_index":0,"filename":"raw-0000.bin","sample_start":"0","sample_end":"8","raw_bytes":"16","chunk_count":1,"crc32":"'+(Hex $crcA)+'","state":"COMPLETE"}' +"`n"+'{"record_type":"SEGMENT_OPEN","segment_index":1,"filename":"raw-0001.bin","sample_start":"8","state":"OPEN"}' +"`n"+'{"record_type":"SEGMENT_COMPLETE","segment_index":1,"filename":"raw-0001.bin","sample_start":"8","sample_end":"16","raw_bytes":"16","chunk_count":1,"crc32":"'+(Hex([HarnessCrc]::U(0,$b)))+'","state":"COMPLETE"}' +"`n"+'{"record_type":"SEGMENT_OPEN","segment_index":2,"filename":"raw-0002.bin","sample_start":"16","state":"OPEN"}' +"`n");$cases+=,$h
$verifier=Join-Path $PSScriptRoot 'verify-long-session-ls5.ps1';$all=$true;foreach($d in $cases){$json=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $verifier -SessionPath $d|Out-String;$r=$json|ConvertFrom-Json;$expected=if((Split-Path $d -Leaf)-in'G_AFTER_SEGMENT_OPEN','H_MULTIPLE_COMPLETE'){'INTERRUPTED_RECOVERABLE'}else{'INTERRUPTED_RECOVERABLE'};$ok=$r.state-eq$expected-and$r.recoverable_raw_bytes-gt0;if((Split-Path $d -Leaf)-eq'E_CHECKPOINT_WRITE'){$ok=$ok-and$r.checkpoint_tail_invalid};$all=$all-and$ok;[pscustomobject]@{case=(Split-Path $d -Leaf);pass=$ok;state=$r.state;recoverable_raw_bytes=$r.recoverable_raw_bytes;unverified_tail_bytes=$r.unverified_tail_bytes;truncated_lines=$r.truncated_jsonl_lines}}
if(!$all){exit 1}
