param([Parameter(Mandatory=$true)][string]$SessionPath)
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $SessionPath).Path
Add-Type -TypeDefinition @'
using System;using System.IO;using System.Text;
public static class Ls5Crc {static readonly uint[] T=B();static uint[] B(){var t=new uint[256];for(uint i=0;i<256;i++){uint c=i;for(int k=0;k<8;k++)c=(c&1)!=0?0xEDB88320U^(c>>1):c>>1;t[i]=c;}return t;}public static uint U(uint s,byte[]b,int n){uint c=~s;for(int i=0;i<n;i++)c=T[(c^b[i])&255]^(c>>8);return ~c;}public static uint Text(string s){var b=Encoding.UTF8.GetBytes(s);return U(0,b,b.Length);}public static uint Range(string p,long o,int l,ref uint aggregate){using(var f=File.OpenRead(p)){f.Position=o;var b=new byte[65536];uint c=0;while(l>0){int n=f.Read(b,0,Math.Min(l,b.Length));if(n<=0)throw new EndOfStreamException();c=U(c,b,n);aggregate=U(aggregate,b,n);l-=n;}return c;}}public static uint FileCrc(string p,ref uint aggregate){using(var f=File.OpenRead(p)){var b=new byte[1048576];uint c=0;int n;while((n=f.Read(b,0,b.Length))>0){c=U(c,b,n);aggregate=U(aggregate,b,n);}return c;}}}
'@
function U64($v){[Convert]::ToUInt64([string]$v,[Globalization.CultureInfo]::InvariantCulture)}
function Lines([string]$p){$valid=@();$bad=0;if(Test-Path -LiteralPath $p){foreach($line in [IO.File]::ReadLines($p)){if(!$line){continue};try{$valid+=,$($line|ConvertFrom-Json)}catch{$bad++}}};[pscustomobject]@{Rows=$valid;Bad=$bad}}
$errors=[Collections.Generic.List[string]]::new();$startPath=Join-Path $root 'session-start.json';$start=$null;if(Test-Path $startPath){try{$start=Get-Content -Raw $startPath|ConvertFrom-Json}catch{$errors.Add('invalid session-start.json')}}
$segLines=Lines (Join-Path $root 'segments.jsonl');$chunkLines=Lines (Join-Path $root 'chunks.jsonl');$indexLines=Lines (Join-Path $root 'chunk-index.jsonl');$eventLines=Lines (Join-Path $root 'events.jsonl');$cpPath=Join-Path $root 'checkpoints.jsonl';$cpRaw=@();$cpBad=$false
if(Test-Path $cpPath){foreach($line in [IO.File]::ReadLines($cpPath)){if(!$line){continue};try{$o=$line|ConvertFrom-Json;$mark=',"record_crc32":"';$p=$line.LastIndexOf($mark);if($p-lt0){$cpBad=$true;continue};$prefix=$line.Substring(0,$p);if(('{0:X8}'-f[Ls5Crc]::Text($prefix))-ne([string]$o.record_crc32).ToUpperInvariant()){$cpBad=$true;continue};$cpRaw+=,$o}catch{$cpBad=$true}}}
$opens=@{};$complete=@{};foreach($s in $segLines.Rows){$i=[uint32]$s.segment_index;if($s.record_type-eq'SEGMENT_OPEN'){$opens[$i]=$s}elseif($s.record_type-eq'SEGMENT_COMPLETE'){$complete[$i]=$s}}
$resultPath=Join-Path $root 'test-result.json';$closed=$false;if(Test-Path $resultPath){try{$closed=[bool]((Get-Content -Raw $resultPath|ConvertFrom-Json).closed)}catch{$errors.Add('invalid test-result.json')}}
$physicalBytes=0L;Get-ChildItem -LiteralPath $root -Filter 'raw-*.bin' -File|ForEach-Object{$physicalBytes+=$_.Length}
$chunkStates=@();$sessionCrc=[uint32]0;$segmentCrc=[uint32]0;$sessionBytes=[uint64]0;$currentSegment=[uint32]0;$expectedOffset=[uint64]0;$lastSample=$null;$overlaps=0L;$sampleGaps=0L;$validChunks=0
foreach($c in $chunkLines.Rows){try{$si=[uint32]$c.segment_index;$off=U64 $c.segment_offset;$n=[int](U64 $c.raw_bytes);$ss=U64 $c.sample_start;$se=U64 $c.sample_end;$file=Join-Path $root ('raw-{0:D4}.bin'-f$si);if(!(Test-Path $file)-or(Get-Item $file).Length-lt([long]$off+$n)){break};if($si-ne$currentSegment){$currentSegment=$si;$expectedOffset=0;$segmentCrc=0};if($off-ne$expectedOffset){break};$chunkAgg=[uint32]0;$crc=[Ls5Crc]::Range($file,[long]$off,$n,[ref]$chunkAgg);if(('{0:X8}'-f$crc)-ne([string]$c.crc32).ToUpperInvariant()){break};$sessionCrc=[Ls5Crc]::U($sessionCrc,[IO.File]::ReadAllBytes($file),0) # no-op, retained type stability
    $buf=[byte[]]::new($n);$fs=[IO.File]::OpenRead($file);$fs.Position=[long]$off;$null=$fs.Read($buf,0,$n);$fs.Dispose();$sessionCrc=[Ls5Crc]::U($sessionCrc,$buf,$n);$segmentCrc=[Ls5Crc]::U($segmentCrc,$buf,$n);$sessionBytes+=[uint64]$n
    if($null-ne$lastSample){if($ss-lt$lastSample){$overlaps++}elseif($ss-gt$lastSample){$sampleGaps++}};$lastSample=$se;$expectedOffset=$off+[uint64]$n;++$validChunks;$chunkStates+=,[pscustomobject]@{Ordinal=[uint64]$validChunks;Seq=U64 $c.seq;Segment=$si;End=$se;SegmentBytes=$expectedOffset;SessionBytes=$sessionBytes;Bytes=[uint64]$n;SegmentCrc=$segmentCrc;SessionCrc=$sessionCrc}
  }catch{break}}
$validCp=$null;foreach($cp in $cpRaw|Sort-Object{U64 $_.checkpoint_id}){$ord=U64 $cp.last_chunk_ordinal;if($ord-ge1-and$ord-le$chunkStates.Count){$st=$chunkStates[[int]$ord-1];if($st.Seq-eq(U64 $cp.last_chunk_seq)-and$st.End-eq(U64 $cp.sample_end)-and$st.SegmentBytes-eq(U64 $cp.segment_raw_bytes)-and('{0:X8}'-f$st.SegmentCrc)-eq([string]$cp.segment_crc32).ToUpperInvariant()-and('{0:X8}'-f$st.SessionCrc)-eq([string]$cp.session_crc32).ToUpperInvariant()){$validCp=$cp}}}
$completeBytes=0L;$completeSegments=0;$manifestCrcErrors=0;$aggregate=[uint32]0;$previousEnd=$null
foreach($i in @($complete.Keys|Sort-Object)){try{$s=$complete[$i];$file=Join-Path $root ([string]$s.filename);if(!(Test-Path $file)){throw};$bytes=U64 $s.raw_bytes;if((Get-Item $file).Length-ne$bytes){throw};$crc=[Ls5Crc]::FileCrc($file,[ref]$aggregate);if(('{0:X8}'-f$crc)-ne([string]$s.crc32).ToUpperInvariant()){$manifestCrcErrors++;continue};$ss=U64 $s.sample_start;if($null-ne$previousEnd-and$ss-ne$previousEnd){$errors.Add("segment boundary $i")};$previousEnd=U64 $s.sample_end;$completeBytes+=[long]$bytes;$completeSegments++}catch{$manifestCrcErrors++}}
$recoverable=[uint64]$completeBytes;$lastChunk=[uint64]0;$lastValidSample=$previousEnd;$checkpointId=$null
if(!$closed-and$validCp){$ord=U64 $validCp.last_chunk_ordinal;$recoverable=[uint64]$chunkStates[[int]$ord-1].SessionBytes;$lastChunk=$ord;$lastValidSample=U64 $validCp.sample_end;$checkpointId=U64 $validCp.checkpoint_id}
elseif($closed-and$validChunks){$recoverable=($chunkStates|ForEach-Object{$_.Bytes}|Measure-Object -Sum).Sum;$lastChunk=[uint64]$validChunks;$lastValidSample=$chunkStates[-1].End}
$tail=[math]::Max(0,[int64]$physicalBytes-[int64]$recoverable);$unclosed=@($opens.Keys|Where-Object{-not$complete.ContainsKey($_)})
if($closed){$state=if($errors.Count-or$manifestCrcErrors-or$validChunks-ne$chunkLines.Rows.Count-or$overlaps){'CORRUPT'}else{'CLOSED'}}elseif($validCp-or$completeSegments){$state='INTERRUPTED_RECOVERABLE'}else{$state='INTERRUPTED_PARTIAL'}
$pass=$state-eq'CLOSED'-and$errors.Count-eq0
[pscustomobject]@{pass=$pass;state=$state;schema_version=$start.schema_version;session_id=$start.session_id;complete_segments=$completeSegments;open_segments=$unclosed.Count;valid_chunks=$validChunks;last_valid_chunk=$lastChunk;last_valid_sample=$lastValidSample;recoverable_raw_bytes=$recoverable;unverified_tail_bytes=$tail;checkpoint_id=$checkpointId;valid_checkpoints=$cpRaw.Count;checkpoint_tail_invalid=$cpBad;valid_events=$eventLines.Rows.Count;active_event_status=if($closed){'NONE'}else{'UNKNOWN_OR_INTERRUPTED'};sample_gaps=$sampleGaps;sample_overlaps=$overlaps;truncated_jsonl_lines=($segLines.Bad+$chunkLines.Bad+$indexLines.Bad+$eventLines.Bad+$(if($cpBad){1}else{0}));segment_crc_failures=$manifestCrcErrors;errors=@($errors);media_verification='PERFORMED_OFFLINE'}|ConvertTo-Json -Depth 4
if(!$pass-and$state-eq'CORRUPT'){exit 3}
